version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: guesstimate-api
      POSTGRES_DB: guesstimate-api_development
    ports:
      - "5432:5432"
