version: "3.1"

services:
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    volumes:
      - .:/docker/app:cached
      - bundle-volume:/usr/local/bundle
    ports:
      - 4000:4000
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: postgres
    restart: always
    # This allows us to use this POSTGRES_MULTIPLE_DATABASES. I use the same image
    # for both the test and development databases
    volumes:
      - ./docker/entry:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: guesstimate-api
      POSTGRES_MULTIPLE_DATABASES: guesstimate-api_development,guesstimate-api_test
    ports:
      - "5432:5432"
volumes:
  bundle-volume:
