name: Rails migration and rspec

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Start containers
        run: docker-compose up -d --build
      - name: Prepare DB
        run: docker-compose run --rm web rails db:prepare
      - name: Run tests
        run: docker-compose run --rm web bundle exec rspec
